BEGIN;

-- Supabase Auth owns credentials in auth.users. Public tables contain only
-- product-facing profile and usage data and are protected by RLS.
CREATE TABLE IF NOT EXISTS public.profiles (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  phone TEXT,
  display_name TEXT,
  phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS profiles_phone_unique_idx
  ON public.profiles (phone)
  WHERE phone IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.user_stats (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  narratives_viewed BIGINT NOT NULL DEFAULT 0 CHECK (narratives_viewed >= 0),
  narratives_saved BIGINT NOT NULL DEFAULT 0 CHECK (narratives_saved >= 0),
  sent_to_go BIGINT NOT NULL DEFAULT 0 CHECK (sent_to_go >= 0),
  launch_plans_created BIGINT NOT NULL DEFAULT 0 CHECK (launch_plans_created >= 0),
  last_active_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.analytics_events (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_name TEXT NOT NULL CHECK (
    event_name IN (
      'session_started',
      'narrative_viewed',
      'narrative_saved',
      'sent_to_go',
      'launch_plan_created'
    )
  ),
  properties JSONB NOT NULL DEFAULT '{}'::jsonb,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS analytics_events_user_time_idx
  ON public.analytics_events (user_id, occurred_at DESC);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;
CREATE POLICY "profiles_select_own"
  ON public.profiles FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "user_stats_select_own" ON public.user_stats;
CREATE POLICY "user_stats_select_own"
  ON public.user_stats FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "analytics_events_select_own" ON public.analytics_events;
CREATE POLICY "analytics_events_select_own"
  ON public.analytics_events FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "analytics_events_insert_own" ON public.analytics_events;
CREATE POLICY "analytics_events_insert_own"
  ON public.analytics_events FOR INSERT
  TO authenticated
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (
    user_id,
    phone,
    display_name,
    phone_verified
  ) VALUES (
    NEW.id,
    COALESCE(NEW.phone, NULLIF(NEW.raw_user_meta_data ->> 'phone', '')),
    NULLIF(NEW.raw_user_meta_data ->> 'display_name', ''),
    NEW.phone_confirmed_at IS NOT NULL
  )
  ON CONFLICT (user_id) DO NOTHING;

  INSERT INTO public.user_stats (user_id)
  VALUES (NEW.id)
  ON CONFLICT (user_id) DO NOTHING;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();

CREATE OR REPLACE FUNCTION public.record_analytics_event(
  requested_event_name TEXT,
  requested_properties JSONB DEFAULT '{}'::jsonb
)
RETURNS public.user_stats
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  current_user_id UUID := auth.uid();
  updated_stats public.user_stats;
BEGIN
  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF requested_event_name NOT IN (
    'session_started',
    'narrative_viewed',
    'narrative_saved',
    'sent_to_go',
    'launch_plan_created'
  ) THEN
    RAISE EXCEPTION 'Unsupported analytics event';
  END IF;

  INSERT INTO public.analytics_events (user_id, event_name, properties)
  VALUES (current_user_id, requested_event_name, COALESCE(requested_properties, '{}'::jsonb));

  INSERT INTO public.user_stats (
    user_id,
    narratives_viewed,
    narratives_saved,
    sent_to_go,
    launch_plans_created,
    last_active_at
  ) VALUES (
    current_user_id,
    CASE WHEN requested_event_name = 'narrative_viewed' THEN 1 ELSE 0 END,
    CASE WHEN requested_event_name = 'narrative_saved' THEN 1 ELSE 0 END,
    CASE WHEN requested_event_name = 'sent_to_go' THEN 1 ELSE 0 END,
    CASE WHEN requested_event_name = 'launch_plan_created' THEN 1 ELSE 0 END,
    NOW()
  )
  ON CONFLICT (user_id) DO UPDATE SET
    narratives_viewed = public.user_stats.narratives_viewed
      + CASE WHEN requested_event_name = 'narrative_viewed' THEN 1 ELSE 0 END,
    narratives_saved = public.user_stats.narratives_saved
      + CASE WHEN requested_event_name = 'narrative_saved' THEN 1 ELSE 0 END,
    sent_to_go = public.user_stats.sent_to_go
      + CASE WHEN requested_event_name = 'sent_to_go' THEN 1 ELSE 0 END,
    launch_plans_created = public.user_stats.launch_plans_created
      + CASE WHEN requested_event_name = 'launch_plan_created' THEN 1 ELSE 0 END,
    last_active_at = NOW(),
    updated_at = NOW()
  RETURNING * INTO updated_stats;

  RETURN updated_stats;
END;
$$;

REVOKE ALL ON FUNCTION public.record_analytics_event(TEXT, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.record_analytics_event(TEXT, JSONB) TO authenticated;

COMMIT;
