create table if not exists public.pulse_narrative_candidates (
  narrative_id text primary key,
  category text not null check (category in (
    'politics_satire', 'events', 'animals_characters',
    'internet_culture', 'ai_tech', 'crypto_native'
  )),
  platform text not null check (platform in ('x', 'news', 'rss')),
  source_type text not null check (source_type in (
    'monitored_account', 'trend_discovery', 'public_feed'
  )),
  author_name text not null,
  original_text text not null,
  source_url text not null unique,
  media_type text,
  media_urls jsonb not null default '[]'::jsonb,
  video_thumbnail_url text,
  published_at timestamptz not null,
  collected_at timestamptz not null,
  expires_at timestamptz not null,
  content_fingerprint text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expires_at <= published_at + interval '1 hour')
);

create index if not exists pulse_narrative_candidates_active_idx
  on public.pulse_narrative_candidates (expires_at desc, category, published_at desc);

create table if not exists public.pulse_narrative_collection_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null,
  completed_at timestamptz,
  status text not null check (status in ('running', 'completed', 'partial', 'failed')),
  source_count integer not null default 0 check (source_count >= 0),
  successful_source_count integer not null default 0 check (successful_source_count >= 0),
  collected_item_count integer not null default 0 check (collected_item_count >= 0),
  eligible_item_count integer not null default 0 check (eligible_item_count >= 0),
  source_status jsonb not null default '[]'::jsonb,
  error_summary text,
  created_at timestamptz not null default now()
);

create index if not exists pulse_narrative_collection_runs_started_idx
  on public.pulse_narrative_collection_runs (started_at desc);

alter table public.pulse_narrative_candidates enable row level security;
alter table public.pulse_narrative_collection_runs enable row level security;
revoke all on public.pulse_narrative_candidates from anon, authenticated;
revoke all on public.pulse_narrative_collection_runs from anon, authenticated;

comment on table public.pulse_narrative_candidates is
  'Short-lived real-source pool for Pulse narrative cards; no synthetic content or AI explanation.';
